# Project information
site_name: Thinking In Code
site_url: https://www.ktyhub.com
site_author: ktyhub
site_description: knowledge thinking you want to know

site_dir: site

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top

extra:
  alternate:
    - name: 中文
      link: /zh/
      lang: zh
    - name: English
      link: /en/
      lang: en

extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/extra.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Copyright
copyright: Copyright &copy; 2022 - 2024 ktyhub.com copyright 转载请注明网站来源


# Page tree
nav:
  - 技术博客:
#    - 前言:
##      # [icon: material/book-open-outline]
#      - 首页: zh/chapter_preface/index.md
#      - 0.1 &nbsp; 关于本书: chapter_preface/about_the_book.md
#      - 0.2 &nbsp; 如何使用本书: chapter_preface/suggestions.md
#      - 0.3 &nbsp; 小结: chapter_preface/summary.md
    - ShardingsphereElasticjob:
      -  分布式弹性调度系统的简介:  zh/chapter_elasticjob/introduce.md
  - 读书笔记:
    - 书籍推荐:
#      # [icon: material/calculator-variant-outline]
      - 首页:  zh/chapter_netty/index.md
