# Project information
site_name: Thinking in code
site_url: https://www.ktyhub.com
site_author: ktyhub
site_description: knowledge thinking you want to know

site_dir: site

theme:
  name: material
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/extra.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Copyright
copyright: Copyright &copy; 2022 - now ktyhub.com copyright


# Page tree
nav:
  - 第 0 章 &nbsp; 前言:
      # [icon: material/book-open-outline]
      - 首页: chapter_preface/index.md
      - 0.1 &nbsp; 关于本书: chapter_preface/about_the_book.md
      - 0.2 &nbsp; 如何使用本书: chapter_preface/suggestions.md
      - 0.3 &nbsp; 小结: chapter_preface/summary.md
  - 第 1 章 &nbsp; Netty:
      # [icon: material/calculator-variant-outline]
      - 首页:  chapter_netty/index.md
